jsonReport: true
htmlReport: true
reportIdentifier: Example Report
timeout: 0
fileWhiteList: []
fileBlackList: 
    - "build\\/"
    - "\\.md"
    - "\\.png"
ignoreBranches:
    - "^release\\-"
    - "^v\\."